name: ldv_backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  dart_frog: ^1.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  postgres: ^3.5.9

dev_dependencies:
  build_runner: ^2.10.4
  dart_frog_lint: ^0.1.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mocktail: ^1.0.3
  test: ^1.25.5
